version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hotel_example_site_restapi
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      ALLOW_ORIGIN: 'localhost:8080'
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc/openapi.yaml:/openapi.yaml
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
